[2024-06-24T09:28:24.739+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T09:28:24.772+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag_for_alerting_final_1.insert_new_record_into_audit_table scheduled__2024-06-24T09:27:00+00:00 [queued]>
[2024-06-24T09:28:24.783+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag_for_alerting_final_1.insert_new_record_into_audit_table scheduled__2024-06-24T09:27:00+00:00 [queued]>
[2024-06-24T09:28:24.783+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-24T09:28:24.797+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_new_record_into_audit_table> on 2024-06-24 09:27:00+00:00
[2024-06-24T09:28:24.802+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1758) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T09:28:24.803+0000] {standard_task_runner.py:63} INFO - Started process 1759 to run task
[2024-06-24T09:28:24.804+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'demo_dag_for_alerting_final_1', 'insert_new_record_into_audit_table', 'scheduled__2024-06-24T09:27:00+00:00', '--job-id', '3455', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag_for_alerting.py', '--cfg-path', '/tmp/tmpdr78yu_u']
[2024-06-24T09:28:24.805+0000] {standard_task_runner.py:91} INFO - Job 3455: Subtask insert_new_record_into_audit_table
[2024-06-24T09:28:24.846+0000] {task_command.py:426} INFO - Running <TaskInstance: demo_dag_for_alerting_final_1.insert_new_record_into_audit_table scheduled__2024-06-24T09:27:00+00:00 [running]> on host bf895605831d
[2024-06-24T09:28:24.931+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_dag_for_alerting_final_1' AIRFLOW_CTX_TASK_ID='insert_new_record_into_audit_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T09:27:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-24T09:27:00+00:00'
[2024-06-24T09:28:24.932+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T09:28:24.944+0000] {logging_mixin.py:188} INFO - insert_into_audit_table_for_adhoc_data
[2024-06-24T09:28:24.944+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-24T09:28:24.944+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T09:28:24.952+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=demo_dag_for_alerting_final_1, task_id=insert_new_record_into_audit_table, run_id=scheduled__2024-06-24T09:27:00+00:00, execution_date=20240624T092700, start_date=20240624T092824, end_date=20240624T092824
[2024-06-24T09:28:24.977+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-24T09:28:24.991+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T09:28:24.993+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
